---
title: "Comparing the T1 & T2 DDPCR Data"
author: "Manogna"
date: "2024-07-12"
output: html_document
---
```{r}
#Load Libraries
 
library(tidyverse)

#load_data

swab_data_clean = read_csv("./data/processed_data/swab_data_clean.csv")
```

```{r}
#DDPCR data of swabs near start of aerosol experiments
ddpcr_data_pre =
  swab_data_clean %>%
  filter(!(samp_id %in% paste0("s",13:20))) %>%
  filter(!(room_id %in% paste0("r3"))) %>%
  group_by(room_id) %>%
  select(room_id,UFT_m2,location) %>%
  drop_na() %>%
  mutate(time = "t1" )


#data of swabs near end of aerosol experiments
ddpcr_data_post =
 swab_data_clean %>%
  filter(!(samp_id %in% paste0("s",1:8))) %>%
  filter(!(room_id %in% paste0("r3"))) %>%
  select(room_id,UFT_m2,location) %>%
  drop_na() %>%
  mutate(time = "t2" )


#create a new table with only pre & post values
combined_ddpcr_timepoint <- bind_rows(ddpcr_data_pre, ddpcr_data_post)

#pivot longer
combined_ddpcr_timepoint_pivot = 
  combined_ddpcr_timepoint %>%
  pivot_wider(names_from = time, values_from = UFT_m2)

library(stats)

#Statistical analysis wilcox
wilcox.test.result.table <- wilcox.test(combined_ddpcr_timepoint_pivot$t1, combined_ddpcr_timepoint_pivot$t2, paired = TRUE)

library(ggplot2)
library(gridExtra)
library(grid)
library(ggstatsplot)

combined_ddpcr_timepoint %>%
  ungroup() %>%
ggbetweenstats(
  x= time,
  y= UFT_m2,
  group = c(room_id,location))
                       
```

```

